//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InventoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InventoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManagement.View.InventoryResource", typeof(InventoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with the same ID already exists. Can&apos;t add product to inventory.
        /// </summary>
        internal static string AddDuplicateError {
            get {
                return ResourceManager.GetString("AddDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Added Successfully in Inventory.
        /// </summary>
        internal static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found. Nothing was deleted..
        /// </summary>
        internal static string DeleteNotFoundError {
            get {
                return ResourceManager.GetString("DeleteNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Deleted Successfully..
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID: {0}
        ///Product Name: {1}
        ///Product Category: {2}
        ///Unit Price: {3}
        ///Stock Quantity: {4}
        ///Total Price: {5}.
        /// </summary>
        internal static string DisplayDetails {
            get {
                return ResourceManager.GetString("DisplayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------.
        /// </summary>
        internal static string DisplayDivider {
            get {
                return ResourceManager.GetString("DisplayDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update product details..
        /// </summary>
        internal static string EditNotFoundError {
            get {
                return ResourceManager.GetString("EditNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Updated Successfully..
        /// </summary>
        internal static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Category Format.
        /// </summary>
        internal static string InvalidCategoryError {
            get {
                return ResourceManager.GetString("InvalidCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Choice (1 to 7).
        /// </summary>
        internal static string InvalidChoiceError {
            get {
                return ResourceManager.GetString("InvalidChoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product ID Format.
        /// </summary>
        internal static string InvalidIDError {
            get {
                return ResourceManager.GetString("InvalidIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Name Format.
        /// </summary>
        internal static string InvalidNameError {
            get {
                return ResourceManager.GetString("InvalidNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid price.
        /// </summary>
        internal static string InvalidPriceError {
            get {
                return ResourceManager.GetString("InvalidPriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Stock Quantity.
        /// </summary>
        internal static string InvalidStockError {
            get {
                return ResourceManager.GetString("InvalidStockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input! The input should not be null or empty and should contain only letters.
        /// </summary>
        internal static string InvalidStringFormat {
            get {
                return ResourceManager.GetString("InvalidStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Products in Inventory.
        /// </summary>
        internal static string InventoryEmptyWarning {
            get {
                return ResourceManager.GetString("InventoryEmptyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Management.
        /// </summary>
        internal static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Add Products to Inventory
        ///2. Edit Products (Using Product ID)
        ///3. Delete Products (Using Product ID)
        ///4. Search product By Name
        ///5. Search product By ID
        ///6. View all Products
        ///7. Exit
        ///Enter Your Choice:.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null Reference has been caught: {0}.
        /// </summary>
        internal static string NullReferenceMessage {
            get {
                return ResourceManager.GetString("NullReferenceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Category:.
        /// </summary>
        internal static string PromptProductCategory {
            get {
                return ResourceManager.GetString("PromptProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product ID (Format: PROD1234):.
        /// </summary>
        internal static string PromptProductID {
            get {
                return ResourceManager.GetString("PromptProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Name:.
        /// </summary>
        internal static string PromptProductName {
            get {
                return ResourceManager.GetString("PromptProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Stock Quantity:.
        /// </summary>
        internal static string PromptStockQuantity {
            get {
                return ResourceManager.GetString("PromptStockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Unit Price:.
        /// </summary>
        internal static string PromptUnitPrice {
            get {
                return ResourceManager.GetString("PromptUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product with the ID is found.
        /// </summary>
        internal static string SearchIDNotFoundError {
            get {
                return ResourceManager.GetString("SearchIDNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Product with the specified name found.
        /// </summary>
        internal static string SearchNameNotFoundError {
            get {
                return ResourceManager.GetString("SearchNameNotFoundError", resourceCulture);
            }
        }
    }
}
