//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedLINQChallenges.PresentationLayer.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedLINQChallenges.PresentationLayer.View.DisplayResource", typeof(DisplayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Product with ID : {0} found, Could not Add Product.
        /// </summary>
        internal static string DuplicateProductError {
            get {
                return ResourceManager.GetString("DuplicateProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average price of all the electronic products above $500: {0}.
        /// </summary>
        internal static string Task1AveragePrice {
            get {
                return ResourceManager.GetString("Task1AveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Task-1:
        ///Electronic Products with price greater than $500 Sorted By Descending order:.
        /// </summary>
        internal static string Task1Title {
            get {
                return ResourceManager.GetString("Task1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Categorized Products:.
        /// </summary>
        internal static string Task2CategorizedHeader {
            get {
                return ResourceManager.GetString("Task2CategorizedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category : {0}.
        /// </summary>
        internal static string Task2CategoryLabel {
            get {
                return ResourceManager.GetString("Task2CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Expensive Product ID: {0}, | Product Name : {1} | Product Price : {2}.
        /// </summary>
        internal static string Task2ExpensiveProductLabel {
            get {
                return ResourceManager.GetString("Task2ExpensiveProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of products : {0}.
        /// </summary>
        internal static string Task2ProductCountLabel {
            get {
                return ResourceManager.GetString("Task2ProductCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Task-2:
        ///Mapping Suppliers with Products:.
        /// </summary>
        internal static string Task2Title {
            get {
                return ResourceManager.GetString("Task2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Task - 4:
        ///Books sorted from Highest to lowest:.
        /// </summary>
        internal static string Task4Title {
            get {
                return ResourceManager.GetString("Task4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Task - 5:
        ///Filter products above 100 and Sort them by price and map them with their suppliers:.
        /// </summary>
        internal static string Task5Title {
            get {
                return ResourceManager.GetString("Task5Title", resourceCulture);
            }
        }
    }
}
