//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListImplementation.PresentationLayer.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListImplementation.PresentationLayer.View.DisplayResource", typeof(DisplayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Add 5 Book Titles to Repo:.
        /// </summary>
        internal static string AddBookTitle {
            get {
                return ResourceManager.GetString("AddBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Books in the Book List.
        /// </summary>
        internal static string BookListHeading {
            get {
                return ResourceManager.GetString("BookListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Searched Book is not found!.
        /// </summary>
        internal static string BookNotFound {
            get {
                return ResourceManager.GetString("BookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete, No Book with this book title found.
        /// </summary>
        internal static string BookNotFoundError {
            get {
                return ResourceManager.GetString("BookNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Title Found!.
        /// </summary>
        internal static string BookTitleFound {
            get {
                return ResourceManager.GetString("BookTitleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Book Title found, Cannot add book to Repo.
        /// </summary>
        internal static string DuplicateBookError {
            get {
                return ResourceManager.GetString("DuplicateBookError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Title should not be null or empty, and should contain only characters.
        /// </summary>
        internal static string InputStringError {
            get {
                return ResourceManager.GetString("InputStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Books found in the Book List!.
        /// </summary>
        internal static string NoBookFound {
            get {
                return ResourceManager.GetString("NoBookFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Book Title: .
        /// </summary>
        internal static string PromptBookTitle {
            get {
                return ResourceManager.GetString("PromptBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Remove Book Title.
        /// </summary>
        internal static string RemoveBookTitle {
            get {
                return ResourceManager.GetString("RemoveBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Search for Book.
        /// </summary>
        internal static string SearchBookTitle {
            get {
                return ResourceManager.GetString("SearchBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Added Successfully!.
        /// </summary>
        internal static string SuccessfulCreation {
            get {
                return ResourceManager.GetString("SuccessfulCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title deleted Successfully!.
        /// </summary>
        internal static string SuccessfulDeletion {
            get {
                return ResourceManager.GetString("SuccessfulDeletion", resourceCulture);
            }
        }
    }
}
