//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryImplementation.PresentationLayer.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DictionaryImplementation.PresentationLayer.View.DisplayResource", typeof(DisplayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Student found, Cannot add Student to Repo.
        /// </summary>
        internal static string DuplicateStudentError {
            get {
                return ResourceManager.GetString("DuplicateStudentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid grade, Grade should be between 1 to 10!.
        /// </summary>
        internal static string InvalidGradeError {
            get {
                return ResourceManager.GetString("InvalidGradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name should not be null or empty, and should contain only characters.
        /// </summary>
        internal static string InvalidStudentNameError {
            get {
                return ResourceManager.GetString("InvalidStudentNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name not found to delete!.
        /// </summary>
        internal static string NameNotFoundToDelete {
            get {
                return ResourceManager.GetString("NameNotFoundToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Grade (1 to 10): .
        /// </summary>
        internal static string PromptGrade {
            get {
                return ResourceManager.GetString("PromptGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Student Name: .
        /// </summary>
        internal static string PromptStudentName {
            get {
                return ResourceManager.GetString("PromptStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Remove Student Details!.
        /// </summary>
        internal static string RemoveStudentHeading {
            get {
                return ResourceManager.GetString("RemoveStudentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Result added Successfully!.
        /// </summary>
        internal static string StudentAddedSuccessfully {
            get {
                return ResourceManager.GetString("StudentAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Student Result Name and Grade.
        /// </summary>
        internal static string StudentDetailsHeading {
            get {
                return ResourceManager.GetString("StudentDetailsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Student Result Found!.
        /// </summary>
        internal static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student result deleted Successfully!.
        /// </summary>
        internal static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
    }
}
