//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BankingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankingSystem.BankingMessages", typeof(BankingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not created. Check Details and Try Again.
        /// </summary>
        internal static string AccountAlreadyExistsError {
            get {
                return ResourceManager.GetString("AccountAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was successfully created.
        /// </summary>
        internal static string AccountCreationSuccessful {
            get {
                return ResourceManager.GetString("AccountCreationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not Created. Check your details and try again.
        /// </summary>
        internal static string AccountNotCreated {
            get {
                return ResourceManager.GetString("AccountNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        internal static string AccountNotFoundError {
            get {
                return ResourceManager.GetString("AccountNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Account Number (Exactly 12 digits):.
        /// </summary>
        internal static string AccountNumberPrompt {
            get {
                return ResourceManager.GetString("AccountNumberPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Account Type (1-Savings, 2-Checking):.
        /// </summary>
        internal static string AccountTypePrompt {
            get {
                return ResourceManager.GetString("AccountTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking System.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount to Deposit:.
        /// </summary>
        internal static string DepositPrompt {
            get {
                return ResourceManager.GetString("DepositPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit successful! New balance: Rs.{0}.
        /// </summary>
        internal static string DepositSuccess {
            get {
                return ResourceManager.GetString("DepositSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Initial amount deposit:.
        /// </summary>
        internal static string InitialDepositPrompt {
            get {
                return ResourceManager.GetString("InitialDepositPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Failed. Insufficient balance in Account..
        /// </summary>
        internal static string InsufficientBalanceError {
            get {
                return ResourceManager.GetString("InsufficientBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number must be exactly 12 numeric digits..
        /// </summary>
        internal static string InvalidAccountNumber {
            get {
                return ResourceManager.GetString("InvalidAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account Type. Must be 1 or 2..
        /// </summary>
        internal static string InvalidAccountType {
            get {
                return ResourceManager.GetString("InvalidAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount greater than 0..
        /// </summary>
        internal static string InvalidAmountError {
            get {
                return ResourceManager.GetString("InvalidAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid initial deposit amount. Minimum Deposit amount is Rs.1000.
        /// </summary>
        internal static string InvalidInitialDeposit {
            get {
                return ResourceManager.GetString("InvalidInitialDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice. Enter choice (1/2/3).
        /// </summary>
        internal static string InvalidMenuChoice {
            get {
                return ResourceManager.GetString("InvalidMenuChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must contain alphabets only. .
        /// </summary>
        internal static string InvalidNameError {
            get {
                return ResourceManager.GetString("InvalidNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU
        ///1. Add Account
        ///2. Withdraw
        ///3. Deposit
        ///4. Exit
        ///Enter Your choice (1/2/3/4):.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum initial deposit should be Rs.1000..
        /// </summary>
        internal static string MinimumDepositError {
            get {
                return ResourceManager.GetString("MinimumDepositError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Account Holder Name:.
        /// </summary>
        internal static string NamePrompt {
            get {
                return ResourceManager.GetString("NamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount to Withdraw:.
        /// </summary>
        internal static string WithdrawPrompt {
            get {
                return ResourceManager.GetString("WithdrawPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal successful! New balance: Rs.{0}.
        /// </summary>
        internal static string WithdrawSuccess {
            get {
                return ResourceManager.GetString("WithdrawSuccess", resourceCulture);
            }
        }
    }
}
