//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3.PresentationLayer.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task3.PresentationLayer.View.DisplayResource", typeof(DisplayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Array Size! Array size must be a positive integer.
        /// </summary>
        internal static string ErrorInvalidArraySize {
            get {
                return ResourceManager.GetString("ErrorInvalidArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Integer format!.
        /// </summary>
        internal static string ErrorInvalidInteger {
            get {
                return ResourceManager.GetString("ErrorInvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be atleast two elements to display the Second Highest Value!.
        /// </summary>
        internal static string ErrorMinimumElements {
            get {
                return ResourceManager.GetString("ErrorMinimumElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pairs found that adds upto the specified target.
        /// </summary>
        internal static string ErrorNoPairsFound {
            get {
                return ResourceManager.GetString("ErrorNoPairsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Array Element {0} :.
        /// </summary>
        internal static string GetArrayElement {
            get {
                return ResourceManager.GetString("GetArrayElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Second Highest Value in the Array: {0}.
        /// </summary>
        internal static string LabelSecondHighest {
            get {
                return ResourceManager.GetString("LabelSecondHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Sum Pairs:.
        /// </summary>
        internal static string LabelTargetSumPairs {
            get {
                return ResourceManager.GetString("LabelTargetSumPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, {1}).
        /// </summary>
        internal static string PairFormat {
            get {
                return ResourceManager.GetString("PairFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Array Elements:.
        /// </summary>
        internal static string PromptArrayElements {
            get {
                return ResourceManager.GetString("PromptArrayElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Array Size:.
        /// </summary>
        internal static string PromptArraySize {
            get {
                return ResourceManager.GetString("PromptArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the target Sum:.
        /// </summary>
        internal static string PromptTargetSum {
            get {
                return ResourceManager.GetString("PromptTargetSum", resourceCulture);
            }
        }
    }
}
