//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorApp.PresentationLayer.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorApp.PresentationLayer.View.DisplayResource", typeof(DisplayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATOR APP.
        /// </summary>
        internal static string CalculatorApp {
            get {
                return ResourceManager.GetString("CalculatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  _________________________________________________
        ///|                                                 |
        ///|                                                 |
        ///|                                                 |
        ///|_________________________________________________|
        ///    [ 1 ]   [ 2 ]   [ 3 ]       [ + ]
        ///    [ 4 ]   [ 5 ]   [ 6 ]       [ - ]
        ///    [ 7 ]   [ 8 ]   [ 9 ]       [ * ]
        ///         [ = (Enter) ]          [ / ]
        ///.
        /// </summary>
        internal static string DisplayCalculatorDesign {
            get {
                return ResourceManager.GetString("DisplayCalculatorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Expression should contain only +, -, *, /, = or numbers and should have atleast one operator and 2 operands.
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mathematical Expression (12+4*7/10): .
        /// </summary>
        internal static string PromptExpression {
            get {
                return ResourceManager.GetString("PromptExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any character to continue.
        /// </summary>
        internal static string PromptForContinue {
            get {
                return ResourceManager.GetString("PromptForContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any character to continue, ESC to escape.
        /// </summary>
        internal static string PromptForEscape {
            get {
                return ResourceManager.GetString("PromptForEscape", resourceCulture);
            }
        }
    }
}
