//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorHandlingTasks.PresentationLayer.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErrorHandlingTasks.PresentationLayer.View.DisplayResource", typeof(DisplayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of Division : {0}.
        /// </summary>
        internal static string DivisionResult {
            get {
                return ResourceManager.GetString("DivisionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth element of the Array: {0}.
        /// </summary>
        internal static string FifthElementOfArray {
            get {
                return ResourceManager.GetString("FifthElementOfArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally Block of Division Operation.
        /// </summary>
        internal static string FinallyBlockStatement {
            get {
                return ResourceManager.GetString("FinallyBlockStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Array Elements: .
        /// </summary>
        internal static string PromptArrayElements {
            get {
                return ResourceManager.GetString("PromptArrayElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Array Size: .
        /// </summary>
        internal static string PromptArraySize {
            get {
                return ResourceManager.GetString("PromptArraySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Dividend: .
        /// </summary>
        internal static string PromptDividend {
            get {
                return ResourceManager.GetString("PromptDividend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Divisor:.
        /// </summary>
        internal static string PromptDivisor {
            get {
                return ResourceManager.GetString("PromptDivisor", resourceCulture);
            }
        }
    }
}
