//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDataProcessorWithAsyncMethods {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilePath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilePath() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileDataProcessorWithAsyncMethods.FilePath", typeof(FilePath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData1.txt.
        /// </summary>
        internal static string Destination1 {
            get {
                return ResourceManager.GetString("Destination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData10.txt.
        /// </summary>
        internal static string Destination10 {
            get {
                return ResourceManager.GetString("Destination10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData2.txt.
        /// </summary>
        internal static string Destination2 {
            get {
                return ResourceManager.GetString("Destination2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData3.txt.
        /// </summary>
        internal static string Destination3 {
            get {
                return ResourceManager.GetString("Destination3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData4.txt.
        /// </summary>
        internal static string Destination4 {
            get {
                return ResourceManager.GetString("Destination4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData5.txt.
        /// </summary>
        internal static string Destination5 {
            get {
                return ResourceManager.GetString("Destination5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData6.txt.
        /// </summary>
        internal static string Destination6 {
            get {
                return ResourceManager.GetString("Destination6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData7.txt.
        /// </summary>
        internal static string Destination7 {
            get {
                return ResourceManager.GetString("Destination7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData8.txt.
        /// </summary>
        internal static string Destination8 {
            get {
                return ResourceManager.GetString("Destination8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedData9.txt.
        /// </summary>
        internal static string Destination9 {
            get {
                return ResourceManager.GetString("Destination9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData1.txt.
        /// </summary>
        internal static string Source1 {
            get {
                return ResourceManager.GetString("Source1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData10.txt.
        /// </summary>
        internal static string Source10 {
            get {
                return ResourceManager.GetString("Source10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData2.txt.
        /// </summary>
        internal static string Source2 {
            get {
                return ResourceManager.GetString("Source2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData3.txt.
        /// </summary>
        internal static string Source3 {
            get {
                return ResourceManager.GetString("Source3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData4.txt.
        /// </summary>
        internal static string Source4 {
            get {
                return ResourceManager.GetString("Source4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData5.txt.
        /// </summary>
        internal static string Source5 {
            get {
                return ResourceManager.GetString("Source5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData6.txt.
        /// </summary>
        internal static string Source6 {
            get {
                return ResourceManager.GetString("Source6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData7.txt.
        /// </summary>
        internal static string Source7 {
            get {
                return ResourceManager.GetString("Source7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData8.txt.
        /// </summary>
        internal static string Source8 {
            get {
                return ResourceManager.GetString("Source8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileData9.txt.
        /// </summary>
        internal static string Source9 {
            get {
                return ResourceManager.GetString("Source9", resourceCulture);
            }
        }
    }
}
